sonar.projectKey=SonarQube-tested-backend-application
sonar.projectName=SonarQube Tested Backend Application

sonar.python.version=3.14
sonar.sources=app

sonar.python.coverage.reportPaths=coverage.xml

sonar.sourceEncoding=UTF-8